### ISSUE TITLE
Output file path

### ISSUE THREAD

**Issue by BamdadTabari** [Dayana-World/DayanaBruteForceListBuilder#7]
the output file path is defined in the code environment.
the user must be able to determine the output file location

**Comment by mostafakavand** [comment]
Yes, this is also an important point.
We will fix this too

**Comment by BamdadTabari** [comment]
> Yes, this is also an important point. We will fix this too

that looks easy

**Comment by mostafakavand** [comment]
I think it should be done in such a way that the user does not have a problem entering the path

**Comment by BamdadTabari** [comment]
> I think it should be done in such a way that the user does not have a problem entering the path

sorry, explain this
